### ISSUE TITLE
Ref to turnstile is always null

### ISSUE THREAD

**Issue by imprakharshukla** [marsidev/react-turnstile#10]
Thank you for this library.
I am trying to reset the captcha after a form submission, but the reference to the turnstile widget is always null.

` const turnstileRef = useRef(null);`

        <Turnstile
            ref={turnstileRef}
            sitekey="0x4AAAAAAACFaH4Vby0ghcqz"
            onVerify={(token) => setCaptchaToken(token)}
            onError={(error) => toast.error(error)}
            onExpire={onExpire}
            autoResetOnExpire={true}
         />

This is my resetting logic-
  
          function resetCaptcha() {
              if (turnstileRef.current) {
                  turnstileRef.current?.reset()
              }
          }
      
          function onExpire() {
              setCaptchaToken(null)
              turnstileRef.current?.reset()
          }

**Comment by marsidev** [comment]
Hello!

Can you provide a repo or codesandbox with your error? [Here is an example](https://codesandbox.io/p/sandbox/react-turnstile-demo-r07fg8?file=%2Fcomponents%2FForm.tsx) of a form with a turnstile widget, which resets after a form submission. With Next.js. Let me know if this helps you.
