### ISSUE TITLE
feat: The width of the widget

### ISSUE THREAD

**Issue by ensidialabs** [marsidev/react-turnstile#14]
Is it possible to make the width of the widget not 300px, but wider?

**Comment by ensidialabs** [comment]
I can do something like that 
```
#cf-turnstile iframe {
  width: 385px !important;
}
```

But perhaps there is a more elegant way?

**Comment by marsidev** [comment]
Hey!

Thank you for your question. Currently, the widget's native [sizes](https://developers.cloudflare.com/turnstile/get-started/client-side-rendering/#widget-size) are 300x65 (normal) and 130x120 (compact), and there is no way to customize its dimensions. While I appreciate that you are looking for greater flexibility, I prefer to respect the sizes provided by Cloudflare. At least for now.
