### ISSUE TITLE
Partytown integration

### ISSUE THREAD

**Issue by BleedingDev** [marsidev/react-turnstile#2]
Hi,
would it be possible to allow Partytown integration? Either via support for completely custom scripts (so that we can use Next.js script tag) or some other way? :)

**Comment by marsidev** [comment]
Hey, I didn't heard about Partytown before, but I'll check it out and try to allow an easy integration in the following days :) 
Also, feel free to contribute if want to 👍🏼

**Comment by pegak** [comment]
I will try to find a time to contribute! I am currently starting a project (fully open source - you can find it on my GH profile, just had soft launch yesterday), so it is hard.

But time will come. :)

**Comment by selenaaasi** [comment]
``Hello, 
I'm trying to add this library inside react application but I'm facing an issue with bable-loader.
Error:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     ...divProps
|   } = props;
>   const config = options ?? {};
|   const widgetSize = config.size ?? "normal";
|   const [widgetId, setWidgetId] = useState();

My package.json: 
`{"dependencies": {
    "@babel/plugin-transform-typescript": "^7.13.0",
    "@marsidev/react-turnstile": "^0.1.2",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "algoliasearch": "^4.3.1",
    "axios": "^0.20.0",
    "babel-plugin-styled-components": "^2.0.2",
    "bowser": "^2.11.0",
    "country-iso-2-to-3": "^1.1.0",
    "date-fns": "^2.15.0",
    "eslint-plugin-import": "^2.22.1",
    "formik": "^2.1.5",
    "fuse.js": "^6.6.2",
    "i18next": "^19.7.0",
    "jsonwebtoken": "^8.5.1",
    "lint-staged": "^10.3.0",
    "lodash.debounce": "^4.0.8",
    "lodash.get": "^4.4.2",
    "lodash.groupby": "^4.6.0",
    "lodash.isempty": "^4.4.0",
    "lodash.isequal": "^4.5.0",
    "lodash.memoize": "^4.1.2",
    "lodash.orderby": "^4.6.0",
    "lodash.startcase": "^4.4.0",
    "lodash.take": "^4.1.1",
    "lodash.upperfirst": "^4.3.1",
    "node-sass": "^7.0.1",
    "numeral": "^2.0.6",
    "owasp-password-strength-test": "^1.3.0",
    "pondjs": "^0.9.0",
    "prettier": "^2.2.1",
    "prop-types": "^15.7.2",
    "qs": "^6.9.6",
    "react": "^16.13.1",
    "react-braintree-fields": "^1.8.0",
    "react-code-input": "^3.10.1",
    "react-currency-input-field": "^3.2.3",
    "react-dom": "^16.13.1",
    "react-google-recaptcha": "^2.1.0",
    "react-gtm-module": "^2.0.11",
    "react-helmet-async": "^1.0.7",
    "react-html-parser": "^2.0.2",
    "react-i18next": "^11.7.2",
    "react-idle-timer": "^4.5.0",
    "react-instantsearch-dom": "^6.7.0",
    "react-intl-tel-input": "^8.0.5",
    "react-motion": "^0.5.2",
    "react-number-format": "^4.4.1",
    "react-phone-number-input": "^3.1.6",
    "react-plaid-link": "^3.0.0",
    "react-redux": "^7.2.1",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^3.4.1",
    "react-select": "^3.1.0",
    "react-slider": "^1.0.11",
    "react-step-progress-bar": "^1.0.3",
    "react-turnstile": "^1.1.0",
    "recharts": "^2.0.9",
    "redux": "^4.0.5",
    "redux-saga": "^1.1.3",
    "reselect": "^4.0.0",
    "storybook": "^6.0.21",
    "styled-components": "^5.2.0",
    "uuidv4": "^6.2.4",
    "yup": "^0.29.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -p 6006 -s public",
    "build-storybook": "build-storybook -s public"
  },
  "prettier": {
    "singleQuote": true,
    "trailingComma": "all"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/core": "^7.11.6",
    "@storybook/addon-actions": "^6.0.21",
    "@storybook/addon-essentials": "^6.0.21",
    "@storybook/addon-links": "^6.0.21",
    "@storybook/client-api": "^6.0.21",
    "@storybook/node-logger": "^6.0.21",
    "@storybook/preset-create-react-app": "^3.1.4",
    "@storybook/preset-scss": "^1.0.2",
    "@storybook/react": "^6.0.21",
    "babel-loader": "^8.1.0",
    "css-loader": "^4.3.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-react": "^7.21.5",
    "eslint-plugin-react-hooks": "^4.2.0",
    "eslint-plugin-security": "^1.4.0",
    "husky": "^4.3.0",
    "pretty-quick": "^3.0.2",
    "react-is": "^16.13.1",
    "sass-loader": "^10.0.2",
    "style-loader": "^1.2.1"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!(lodash-es|react-intl-tel-input|react-step-progress-bar)/)"
    ]
  },
  "lint-staged": {
    "*.js": [
      "prettier --write",
      "eslint --fix",
      "git add"
    ]
  }`
Do you have an idea what can cause this issue? 
Thanks

**Comment by pegak** [comment]
Are you working on React Turnstile with Partytown or why this thread?

**Comment by marsidev** [comment]
Hey @selenaaasi, please [create a new issue](https://github.com/marsidev/react-turnstile/issues/new/choose) if is not related with this one. Also would be helpful if you provide a minimal reproducible example and info about your stack (framework, node version, etc). 

Thank you

**Comment by ryanSN** [comment]
Would this _just_ work?

just do this in the component you are using this in. (Next will move this script to the head)
```typescript
import Script from 'next/script'

<Script id="cf-turnstile-script" src="https://challenges.cloudflare.com/turnstile/v0/api.js" />
```

This logic _should_ pick it up https://github.com/marsidev/react-turnstile/blob/4e15131bd557c617c9f938292c5b8fc6e643b529/packages/lib/src/utils.ts#L31

At most maybe export the `DEFAULT_SCRIPT_ID` so it can 100% be the same. 🤷🏻‍♂️

**Comment by marsidev** [comment]
Hey @ryanSN, your question is in order to support Partytown?

In any case, the library injects the script for itself. If you manually add the script you can have a duplicated turnstile script.

May be good if we add a `injectScript?: boolean` property, in case we need, _for any reason_, inject the script manually. The usage might be something like this:

```jsx
import { DEFAULT_ONLOAD_NAME, DEFAULT_SCRIPT_ID, Turnstile } from '@marsidev/react-turnstile'
import Script from 'next/script'

export default function Widget() {
  return (
    <>
      <Script
        id={DEFAULT_SCRIPT_ID}
        src={`https://challenges.cloudflare.com/turnstile/v0/api.js?onload=${DEFAULT_ONLOAD_NAME}`}
        strategy="afterInteractive"
      />

      <Turnstile
        injectScript={false}
        siteKey='1x00000000000000000000AA'
      />
    </>
  )
}
```

If using custom script id or custom onLoad callback name:

```jsx
import { Turnstile } from '@marsidev/react-turnstile'
import Script from 'next/script'

export default function Widget() {
  return (
    <>
      <Script
        id="turnstile-script"
        src="https://challenges.cloudflare.com/turnstile/v0/api.js?onload=turnstile-cb"
        strategy="afterInteractive"
      />

      <Turnstile
        injectScript={false}
        scriptOptions={{
          id: 'turnstile-script',
          onLoadCallbackName: 'turnstile-cb',
        }}
        siteKey='1x00000000000000000000AA'
      />
    </>
  )
}
```

I think I'm gonna add it in the next release. If you have any other question or suggestion please use [this issue](https://github.com/marsidev/react-turnstile/issues/15)

**Comment by ryanSN** [comment]
@marsidev , I've never used Partytown Personally but looking its just built on nextjs.  

The initial Request
> support for completely custom scripts (so that we can use Next.js script tag)

So the request was looking to use the Nextjs script tag, so yes, what you are suggesting above would solve this request. I just recently implemented this in a nextjs app and ran into a similar desire (how I got to this ticket) :)

**Comment by marsidev** [comment]
> The initial Request
> 
> > support for completely custom scripts (so that we can use Next.js script tag)
> 
> So the request was looking to use the Nextjs script tag, so yes, what you are suggesting above would solve this request. I just recently implemented this in a nextjs app and ran into a similar desire (how I got to this ticket) :)

I see, thanks for suggesting it! I'll add it on `v0.1.3`.
