### ISSUE TITLE
conditional render only if interaction required

### ISSUE THREAD

**Issue by sgoodluck** [marsidev/react-turnstile#22]
Using this library I noticed that if we set 

```
<Turnstile
   ...
   options={{
     appearance: 'interaction-only',
    }}
/>
```

That the widget immediately vanishes on success.

Widget is invisible if no-interaction is required
Widget becomes visible if interaction required
Widget remains visible after interaction

**Comment by marsidev** [comment]
Hello @sgoodluck, I don't fully understand the issue or request here.

According to [the docs](https://developers.cloudflare.com/turnstile/get-started/client-side-rendering/#appearance-modes), that's how it works when `appearance` is set to `interaction-only`; the widget will remain invisible until it requires manual interaction.

**Comment by marsidev** [comment]
Yes, that's intended. 

Please see [this codesandbox](https://codesandbox.io/s/blissful-williams-ms6usk?file=/src/App.tsx) where I'm rendering two widgets; one is created by `@marsidev/react-turnstile` and the other is a vanilla widget (no libraries). Both have the same behavior.

**Comment by sgoodluck** [comment]
Roger -- will go upstream to cloudflare as that seems like a bug. Thank you for your work on this package!
