### ISSUE TITLE
Error: [Cloudflare Turnstile] Widget vihta to reset was not found..

### ISSUE THREAD

**Issue by mtn020990** [marsidev/react-turnstile#24]
when Turnstile got an error and we move to another page, Turnstile throws an error (see image)
 "@marsidev/react-turnstile": "^0.2.1"
<img width="543" alt="image" src="https://github.com/marsidev/react-turnstile/assets/7200732/d7981846-2de0-4867-8f8e-2068aabbff70">

**Comment by marsidev** [comment]
Hey! Thanks for submitting an issue. 

Can you please provide more context about your stack/environment and share a reproducible example? Thanks in advance.

**Comment by mtn020990** [comment]
I used the aways blocks key here: https://developers.cloudflare.com/turnstile/reference/testing/
<img width="139" alt="image" src="https://github.com/marsidev/react-turnstile/assets/7200732/5fae8136-c56a-4954-bbf8-58c6391fd457">
the Turnstile widget auto-retry the challenge and I move to another page, it got that issue, I guess that the widget was destroyed but the code still get it to reset.
I used React 18.

**Comment by marsidev** [comment]
Hey,

I was not able to reproduce the error. Check [this codesandbox](https://codesandbox.io/p/sandbox/sharp-stallman-vh2z3s?file=%2Fapp%2Fpage.tsx%3A4%2C61) where I tried to replicate it.

Anyways, I added a `try catch` on the `.reset()` method to avoid the error (9bd3d9d017e859bd57103231f4c36df77785035f)

**Comment by enlivn** [comment]
@marsidev thanks for this library. I still see this crash on the following edge case: I'm using a valid turnstile site key and secret but on a domain that is unsupported (ie it is not configured as one of the domains on CF). 

This would definitely fall under the category of programmer error but I wonder if we could fail more gracefully for new people adopting the library.

Stack track:

```
Uncaught TurnstileError: [Cloudflare Turnstile] Widget vz1i9 to reset was not found..
    u https://challenges.cloudflare.com/turnstile/v0/api.js?onload=onloadTurnstileCallback__cf-turnstile&render=explicit:1
    Xt https://challenges.cloudflare.com/turnstile/v0/api.js?onload=onloadTurnstileCallback__cf-turnstile&render=explicit:1
    t https://challenges.cloudflare.com/turnstile/v0/api.js?onload=onloadTurnstileCallback__cf-turnstile&render=explicit:1
    v https://challenges.cloudflare.com/turnstile/v0/api.js?onload=onloadTurnstileCallback__cf-turnstile&render=explicit:1
    S https://challenges.cloudflare.com/turnstile/v0/api.js?onload=onloadTurnstileCallback__cf-turnstile&render=explicit:1
    retryTimeout https://challenges.cloudflare.com/turnstile/v0/api.js?onload=onloadTurnstileCallback__cf-turnstile&render=explicit:1
```
