### ISSUE TITLE
appearance on interaction-only has width and height

### ISSUE THREAD

**Issue by tnfAngel** [marsidev/react-turnstile#27]
**Bug report**

**What is the current behavior?**

The component has width and height other than 0 when the appearance is on interaction-only
![imagen](https://github.com/marsidev/react-turnstile/assets/57068341/8c85efab-3447-44f4-b643-54a3bfbf1a63)
![imagen](https://github.com/marsidev/react-turnstile/assets/57068341/0aa12b80-e11f-4bef-bdb7-291d4fd72396)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your [CodeSandbox](https://codesandbox.io/s/new) example below:**
Set the appearance to interaction-only

**What is the expected behavior?**
The component must have width and height of 0, and if an interaction is required, set the correct width and the correct height (this is the default behavior of the cloudflare official script) 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Firefox, Windows. Deps: 
    "next": "13.4.12",
    "react": "18.2.0"

**Comment by flacial** [comment]
For anyone having this problem, try to give each [widget a unique ID](https://docs.page/marsidev/react-turnstile/multiple-widgets).
