### ISSUE TITLE
sitekey was not provided

### ISSUE THREAD

**Issue by gbagush** [marsidev/react-turnstile#39]
```
<Turnstile
    siteKey={process.env.SITE_KEY}
/>
```
i already import dotenv but its show sitekey was not provided

**Comment by CanopusFalling** [comment]
What was the solution to this? I'm currently stuck with either the same or a similar problem.

**Comment by gbagush** [comment]
> What was the solution to this? I'm currently stuck with either the same or a similar problem.

I use nextjs, so the env variable must begin with NEXT_PUBLIC_ so that it can be accessed on the client side

https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables

**Comment by CanopusFalling** [comment]
Ah, thanky for the reply, unfortunately that wasn't it for me (think I'm running into some strange behaviour with edge, turnstile and wrangler all fighting.)
