### ISSUE TITLE
Cannot import module, unexpected token

### ISSUE THREAD

**Issue by advaith1** [marsidev/react-turnstile#4]
When I try to import the package, I get an error:
```
./node_modules/@marsidev/react-turnstile/dist/index.mjs
Module parse failed: Unexpected token (12:51)
You may need an appropriate loader to handle this file type.
|   onLoadCallbackName,
|   onLoad,
|   scriptOptions: { nonce = "", defer = true, async = true, id = "", appendTo } = {}
| }) => {
|   const scriptId = id || DEFAULT_SCRIPT_ID;
```

Line 12 is
```js
  scriptOptions: { nonce = "", defer = true, async = true, id = "", appendTo } = {}
```

The issue appears to be that it's using `async` as a parameter name.

**Comment by marsidev** [comment]
Hey! Do you have a way reproduce the error? such a codesanbox or stackblitz link. 

Or at least provide some context info such as node version, react version, are you using a framework or not.

Here is a [codendbox](https://codesandbox.io/s/kind-dijkstra-21c38t?file=/src/App.js) using the latest version of this library.

**Comment by advaith1** [comment]
We're using react and react-dom 17.0.1, react-app-rewired 1.6.2, and react-scripts-ts 2.17.0.

I couldn't reproduce this issue when modifying your codesandbox to use these dependencies (or when pasting our whole package.json), but if I import our whole repo (without react-turnstile) into codesandbox it has many errors that do not happen locally, so I guess there's some environment difference there. Maybe it's using a different Babel config or something.

I'm using Node v16.14.0 locally.

[Here's a link to our repo](https://github.com/widgetbot-io/embed) without react-turnstile. Simply installing the library and adding
```js
import { Turnstile } from '@marsidev/react-turnstile'
Turnstile
```
to a file (for example src/index.tsx) is enough to cause the error for me.

**Comment by marsidev** [comment]
Hey, I checked your repo and I could not found the reason of the failure. But seems is related to babel or webpack rather than react-turnstile, check out the following links

> ["You may need an appropriate loader to handle this file type" with Webpack and Babel](https://stackoverflow.com/questions/33469929/you-may-need-an-appropriate-loader-to-handle-this-file-type-with-webpack-and-b)

> [Preset files are not allowed to export objects](https://stackoverflow.com/questions/49182862/preset-files-are-not-allowed-to-export-objects)

> [how to fix You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file with webpack 4](https://stackoverflow.com/questions/58562201/how-to-fix-you-may-need-an-appropriate-loader-to-handle-this-file-type-currentl)

Maybe you need to use Babel v7+ as is mentioned [here](https://stackoverflow.com/a/61536062/16011210).
