### ISSUE TITLE
Invalid domain. Contact the site administrator if the problem persists.

### ISSUE THREAD

**Issue by 101budspencer** [marsidev/react-turnstile#42]
Error: Invalid domain. Contact the site administrator if the problem persists.

How could I use it on localhost 3000?

**Comment by marsidev** [comment]
You can either add `localhost` to your list of trusted domains in your [Domain Settings](https://developers.cloudflare.com/turnstile/reference/domain-management/) or use a [testing sitekey](https://developers.cloudflare.com/turnstile/reference/testing/#dummy-sitekeys-and-secret-keys) in development.

**Comment by 101budspencer** [comment]
Yes, thanks I found that already: https://developers.cloudflare.com/turnstile/reference/testing/

And how would you do it with protecting content? I want to a specific div only after verification and it needs to be secure.

My idea:
Passing the encrypted content to the client component, then returning the decryption key if the /api/verify was successfull.

But no idea if it's secure.
How would you do it?

**Comment by marsidev** [comment]
Yeah, that looks good to me. 👍🏽
