### ISSUE TITLE
Widgets Mode: Invisible

### ISSUE THREAD

**Issue by omararturo** [marsidev/react-turnstile#52]
**Mode invisible feature**

**Current behavior**
The component continues to show the widget container even if it is in invisible mode

![image](https://github.com/marsidev/react-turnstile/assets/3682957/8c0eafe4-32ae-4ae9-98b6-6f240d5db713)

**Expected behavior**
Component should not show UI when mode is invisible

![image](https://github.com/marsidev/react-turnstile/assets/3682957/8f1f81aa-7c0e-4cd4-a4c0-888248e01b38)

**Comment by marsidev** [comment]
Did you set `options={{ size: "invisible" }}`?

**Comment by marsidev** [comment]
You need both a valid invisible `siteKey` and this property in your `Turnstile` component

`options={{ size: "invisible" }}`

**Comment by omararturo** [comment]
If the configuration is changed from the Cloudflare server, the plugin detects that it is invisible, but the container does not take that behavior into account.

![image](https://github.com/marsidev/react-turnstile/assets/3682957/608dc6dd-9a9e-4622-8a95-6d8ecae9f75f)

**Comment by marsidev** [comment]
The library is not smart enough to auto-detect invisible site keys. Even by using the vanilla Turnstile widget, there will be a container around the widget.

Again, you need to explicitly pass `size: 'invisible'` to the component. So, on our end, we set width and height to 0. [Example](https://codesandbox.io/p/devbox/react-turnstile-invisible-vvoxkh?file=%2Fsrc%2FApp.tsx%3A4%2C1)

**Comment by marsidev** [comment]
Hey @harrygr,

not sure if we can know what size (compact/normal/invisible) the widget is. If you have an idea, feel free to create a PR in a new issue.

**Comment by harrygr** [comment]
Hey @marsidev. What I was suggesting was a size option that didn't apply any width or height to the widget, just letting it be its own size. Having experimented with a barebones integration it seems like the only reason to set the width/height is to prevent layout shift when there's a delay in the widget loading.

I'll have a go at a PR
