### ISSUE TITLE
Cloudflare Turnstile resource preloading warning with Nextjs 14

### ISSUE THREAD

**Issue by immdraselkhan** [marsidev/react-turnstile#53]
The resource https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/g/cmg/1/CJEbi4RwSjcdqgfNhtiGiFEnzHMCmQfIt6hQ%2F6mE96Y%3D was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

<img width="1728" alt="SCR-20240205-rtfn" src="https://github.com/marsidev/react-turnstile/assets/52624987/32738f60-b108-4232-bf98-141761e5f850">

**Comment by marsidev** [comment]
This warning also appears by using a [vanilla Turnstile Widget](https://demo.turnstile.workers.dev/), so I guess it's unrelated to this library.

![image](https://github.com/marsidev/react-turnstile/assets/56328053/d3343aba-bb88-421b-9a87-4c1bf639eaab)

Feel free to suggest or contribute a fix to this problem.
