### ISSUE TITLE
Widget disappears when the component rerenders

### ISSUE THREAD

**Issue by bgmort** [marsidev/react-turnstile#56]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
I'm rendering the Turnstile component in a form on a next.js 13 app router page. The form rerenders as other fields on the form are updated, and as soon as the Turnstile component rerenders, the widget disappears. I have isolated the behavior to be when the `onWidgetLoad` prop (and possibly others) is passed an inline callback vs one with referential equality.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your [CodeSandbox](https://codesandbox.io/s/new) example below:**
https://codesandbox.io/p/devbox/cloudflare-turnstile-interaction-only-forked-j5fh25

**What is the expected behavior?**
The widget should be able to hander rerenders without disappearing

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

18.2.0, but likely any version of React. Found with @marsidev/react-turnstile@0.5.3.

**Comment by EmanueleBrotti** [comment]
just tryed your example and in my env. It happens only when onWidgetLoad has a function. It gets called on the first rerender and then deleted

**Comment by sarahbangg** [comment]
> just tryed your example and in my env. It happens only when onWidgetLoad has a function. It gets called on the first rerender and then deleted

I was also having a similar bug where onWidgetLoad() would log out but upon inspection, it wouldn't be rendered on the page (although it is technically in the html- just blank).

I commented out the onWidgetLoad prop and I don't seem to be getting that error anymore. Seems like that prop causes the widget to render blank sometimes.

**Comment by marsidev** [comment]
Thanks for letting me know about this issue, and I'm sorry for the delay in fixing it.
It should be fixed in version `0.6.0`
