### ISSUE TITLE
Is it possible to tell if the captcha is visible?

### ISSUE THREAD

**Issue by sketchbuch** [marsidev/react-turnstile#57]
I want to add a spacing between it and some buttons, but only when it is visible

**Comment by marsidev** [comment]
You can use the `onBeforeInteractive` callback, which runs before the challenge becomes interactive.

Example:

```jsx
import { Turnstile } from '@marsidev/react-turnstile'
import React from 'react'

export default function Page() {
  const [isVisible, setIsVisible] = React.useState(false)

  return (
    <React.Fragment>
      <Turnstile
        siteKey="3x00000000000000000000FF"
        onBeforeInteractive={() => setIsVisible(true)}
      />

      {isVisible && <button>Conditional Button</button>}
    </React.Fragment>
  )
}
```

**Comment by sketchbuch** [comment]
yeah, but I want to know if it is visible. After `onAfterInteractive` fires it can still be visible. Because of this, when `onBeforeInteractive` fires it xcan already be visible.

**Comment by marsidev** [comment]
We don't have a `onVisible` callback, but we you can use the [ResizeObserver API](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) to achive what you need. Check [this demo](https://codesandbox.io/p/devbox/sweet-dream-s7gcmn).
