### ISSUE TITLE
Make an invisible Turnstile component show up for forced challenge?

### ISSUE THREAD

**Issue by crisog** [marsidev/react-turnstile#59]
Sometimes the verification prompts for a manual verification, but if the component has been set to 'invisible' it won't show up. 

<img width="531" alt="image" src="https://github.com/marsidev/react-turnstile/assets/40803711/87cf1f78-4c45-4f3b-aa5c-52c62639dafd">

Is there a way we can make it so if the challenge requires interactive action it turns visible? or would this be too complicated.

**Comment by jayhemsley** [comment]
Managed mode is the only way that this can be done, it would be pointless to use the Invisible and Non-Interactive modes with this method. You can conditionally show it though when it has to show up via `onBeforeInteractive` like this:

```
'use client';

export function CaptchaInput({
  className,
  name,
}: CaptchaInputProps): React.ReactElement<CaptchaInputProps> {
  const [captchaVisible, setCaptchaVisible] = useState<boolean>(false);
  const [captchaToken, setCaptchaToken] = useState<string>('');

  const { register, setValue } = useFormContext();

  useEffect(() => {
    if (captchaToken) setValue(name, captchaToken);
  }, [captchaToken]);

  return (
    <div
      className={cn([
        !captchaVisible && 'hidden',
        className,
      ])}>
      <input
        className="hidden"
        type="hidden"
        {...register(name, {
          required: true,
        })}
      />
      <Turnstile
        siteKey={xxx}
        onSuccess={(token) => setCaptchaToken(token)}
        onBeforeInteractive={() => setCaptchaVisible(true)}
      />
    </div>
  );
}
```

**Comment by marsidev** [comment]
As @jayhemsley suggested, the `onBeforeInteractive` property it's what you need.

Also, the `'invisible'` setting should be used when the Widget Mode is invisible too.

**Comment by marsidev** [comment]
Hey @angelhodar, good question.

`size: invisible` is intended to be used for [Invisible Widget Types](https://developers.cloudflare.com/turnstile/concepts/widget-types/#invisible) to prevent reserving a space that will never be used. 

Feel free to check this [PR](https://github.com/marsidev/react-turnstile/pull/9) and this [issue](https://github.com/marsidev/react-turnstile/issues/8) by @chez14 

If you have an idea to improve this behavior, feel free to contribute.

**Comment by angelhodar** [comment]
Thank you so much @marsidev !! So what is the use case of invisible widget types vs managed ones with appearance in ``interaction-only``. Just the space that its used? I see the second one even more flexible in case interaction is needed

**Comment by marsidev** [comment]
> [Invisible widget​​](https://developers.cloudflare.com/turnstile/concepts/widget-types/#invisible): Visitors will never interact with the Turnstile widget. Visitors will not see a widget or any indication that an invisible browser challenge is in progress.

> Managed widget w/ [`interaction-only`](https://developers.cloudflare.com/turnstile/get-started/client-side-rendering/#appearance-modes) appearance: The widget will become only visible in cases where an interaction is required.
