### ISSUE TITLE
What is the proper way to handle multiple submits with captcha approach?

### ISSUE THREAD

**Issue by angelhodar** [marsidev/react-turnstile#6]
Hey! First I wanted to thank you for the amazing library, it works like a charm. I was wondering what is the proper way to handle a secured captcha submit form when the user can click more than once but with different parameters. It feels a bit weird to reset the widget to generate a new token to be submitted if I already know that the current user is legit. One solution would be to redirect to a new page with the result of the form but it would be a pain for my user case. Maybe a little cache in the vercel function with the user ip would do the trick? Thanks in advance!

**Comment by marsidev** [comment]
Hey, thank you! Can you please provide a reproducible repo or preview of the issue that you are facing? To fully understand what you are describing.

**Comment by angelhodar** [comment]
@marsidev Sure! Here you have a codesandbox example: https://codesandbox.io/s/misty-tdd-qkmqn7?file=/src/App.js

The core of the question would be in the Form component, after the submit is completed in the ``finally`` I have to reset the widget, otherwise new submits would fail as the token is the same (unless page is refreshed)

**Comment by marsidev** [comment]
Thanks for the repro. As [the docs](https://developers.cloudflare.com/turnstile/get-started/server-side-validation/) says, a token can be validate only once.

> A response may only be validated once. If the same response is presented twice, the second and each subsequent request will generate an error stating that the response has already been consumed.

If you need to validate a token multiple times, you need to reset the widget. One way is manually reseting it after the validation - as you did it.

Another way could be setting a dynamic cData. If the cData changes, the widget will reset as well. Something like this:

```jsx
function Form() {
  const formRef = useRef(null)
  const [cData, setCData] = useState(Date.now().toString())

  async function handleSubmit(e) {
    e.preventDefault()
    const formData = new FormData(formRef.current)
    const token = formData.get('cf-turnstile-response')
    const username = formData.get('username')
    const password = formData.get('password')

    const res = await fetch('/api/verify', {
      method: 'POST',
      body: JSON.stringify({ token, username, password }),
      headers: {
        'content-type': 'application/json'
      }
    })

    const data = await res.json()
    if (data.success) {
      // the token has been validated

      setCData(Date.now().toString()) // this will reset the widget
    }
  }

  return (
    <form ref={formRef} onSubmit={handleSubmit}>
      <input type="text" name="username" />
      <input type="password" name="password" />
      <Turnstile siteKey={siteKey} options={{ cData }} />
      <button type='submit'>Login</button>
    </form>
  )
}
```

Maybe a trick to avoid reseting the widget could be reading the validation response and check if the error codes contains `timeout-or-duplicate`. Something like this:

```jsx
async function handleSubmit(e) {
  e.preventDefault()
  // ...

  const res = await fetch('/api/verify', {
    method: 'POST',
    body: JSON.stringify({ token, username, password }),
    headers: {
       content-type': 'application/json'
    }
  })

  const data = await res.json()
  if (data.success || data['error-codes']?.includes('timeout-or-duplicate')) {
    // ...
  }
}
```

This is what the validation returns when a token has already being validated:
```json
{
  "success": false,
  "error-codes": [
    "timeout-or-duplicate"
  ],
  "messages": []
}
```

**Comment by angelhodar** [comment]
@marsidev Thank you so much for your answer! So I was going in the right direction as I can see. The last suggestion seems pretty fine and could be implemented by passing an extra boolean to my ``verifyCaptcha`` function like ``lax`` or something to not be very strict in the validation and allow that "timeout-or-duplicate" option, but I dont know if it is considered as a bad practice because of security issues, isnt it?

**Comment by marsidev** [comment]
I'm not sure neither, but I'd go with the "`timeout-or-duplicate`" option if reseting the widget is painful. In that case, maybe you should also ensure `data['error-codes']?.length === 1`
