### ISSUE TITLE
Turnstile doesn't work on iOS app

### ISSUE THREAD

**Issue by sarahbangg** [marsidev/react-turnstile#60]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I have a React app that renders on an iOS app using WebView from react-native-webview. Recently, the Turnstile captcha has been failing on only the iOS app. It works on desktop browser, android mobile browser, ios mobile/tablet browser, but not ios app.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React v16.13.1 on devices with the most recent iOS version (4/10/24). It has always worked with this React version. The Podfile for the react native iOS app contains `platform :ios, '12.0'`

**Comment by sarahbangg** [comment]
Nevermind, this seems to be an issue with Turnstile support itself. Recent documentation shows Turnstile no longer supports native apps including webview. See more here: https://community.cloudflare.com/t/turnstile-no-longer-working-inside-of-ios-apps-in-wkwebview/637940  

Feel free to close this issue if nobody has any supporting comments.

**Comment by dmelo** [comment]
Actually, the documentation is currently stating that it should work on native app through web view https://developers.cloudflare.com/turnstile/get-started/mobile-implementation/ . Anyway to get this working on iOS?

**Comment by marsidev** [comment]
As I'm not familiarized with mobile development, React Native, Swift or Kotlin, I'm not able to add this feature at this moment.

Feel free to contribute. 💡

**Comment by dmelo** [comment]
Hey. I think I've figured it out. The page with turnstile is inside a WebView element. That WebView needs `originWhitelist` to be correctly set. Like this:

``` 
        <WebView
          source={{
            uri: forgotPasswordURL,
          }}
          ref={webviewRef}
          mixedContentMode="always"
          originWhitelist={["*"]}
         ....
```

**Comment by joevin-slq-docto** [comment]
> Hey. I think I've figured it out. The page with turnstile is inside a WebView element. That WebView needs `originWhitelist` to be correctly set. Like this:
> 
> ```
>         <WebView
>           source={{
>             uri: forgotPasswordURL,
>           }}
>           ref={webviewRef}
>           mixedContentMode="always"
>           originWhitelist={["*"]}
>          ....
> ```

Is there a way to set `originWhitelist` directly from `<Turnstile`> react component?

**Comment by marsidev** [comment]
Nice finding!

**Comment by joevin-slq-docto** [comment]
We faced the exact same issue and it's now working with `originWhitelist`, thanks @dmelo !

**Comment by joevin-slq-docto** [comment]
> We faced the exact same issue and it's now working with `originWhitelist`, thanks @dmelo !

After more investigations, we found out that it's only `about:blank` and `about:srcdoc` that are required to be whitelisted to make Turnstile work.

Examples : 
- `originWhitelist={['http://', 'https://', 'about:']}`
- `onShouldStartLoadWithRequest={event => ['challenges.cloudflare.com', 'about:blank', 'about:srcdoc'].some(url => event.url.includes(url))}`
