### ISSUE TITLE
Multiple widgets vs one on a page?

### ISSUE THREAD

**Issue by NickWoodward** [marsidev/react-turnstile#62]
Hey Marsidev, just wanted to say thanks for a great package, it's been much more of a pleasure to work with than turnstile itself (and your docs are better) :D

Just wanted to ask a quick question if that's ok: If I can get the current response from the widget, can I just reference it and use it for multiple different forms across a page? or do I *need* to have multiple widgets? Basically just wondering what the practical difference are here?

Thanks again, appreciate the work!

**Comment by marsidev** [comment]
Hey Nick,
I'm not sure which one makes more sense, but I'd use one widget per submit button. 
If each form has its own submit button, then 1 widget per form.

**Comment by marsidev** [comment]
Feel free to ask Turnstile-specific questions on the [Cloudflare forum](https://community.cloudflare.com/c/website-application-performance/turnstile/83)
