### ISSUE TITLE
Is there way to get Client Error Codes of turnstile via the library?

### ISSUE THREAD

**Issue by Bigbhardwaj** [marsidev/react-turnstile#67]
It seems that while the Cloudflare documentation mentions the ability to retrieve client error codes through an error callback, this feature isn't currently available in the @marsidev/react-turnstile library. Adding this capability to the library on `onError` prop would enable users to capture client error codes during the error callback.

![image](https://github.com/marsidev/react-turnstile/assets/9026778/949ea8ef-84ad-4aed-8929-9e251956c67b)
  

![image](https://github.com/marsidev/react-turnstile/assets/9026778/9c3cbe20-a78d-40fb-9116-b1f90d5c7d14)

**Comment by marsidev** [comment]
Actually, the error code is being returned in the error callback.

However, the TypeScript definition in the library is wrong. It will be fixed in next release. 👍🏽 

![image](https://github.com/marsidev/react-turnstile/assets/56328053/1e2168a4-7586-4c36-abf4-86880e2912fe)

**Comment by Bigbhardwaj** [comment]
Thanks @marsidev for a quick response!, Do you any visibility when it could be released?

**Comment by marsidev** [comment]
It's available now in `v0.6.1`, @Bigbhardwaj
