### ISSUE TITLE
Prevent Content Layout Shift by Setting the Component Height

### ISSUE THREAD

**Issue by chez14** [marsidev/react-turnstile#7]
In current implementation, there is no height set while the component is loading, this means while loading the captcha, the height of the component is zero. After it loads, the captcha will now have non-zero height (if the captcha is not invisible). This causes content layout shift on the page.

| Actual | Expected |
|---------|---------------|
| <video src="https://user-images.githubusercontent.com/5555026/211140327-f272dd4c-30ca-4ff2-a7de-2c080206882f.mp4"/>  | <video src="https://user-images.githubusercontent.com/5555026/211140348-ca3af577-9698-4e7c-8bf6-287dc7223802.mp4)"/> |

Cloudflare have [properly documented the size of the captcha widget](https://developers.cloudflare.com/turnstile/get-started/client-side-rendering/#widget-size): 

| Size | Width | Height |
| -- | -- | -- |
| Normal | 300px | 65px |
| Compact | 130px | 120px |

So with these information, I think we can create somekind of space/placeholder for the widget (i.e `min-width: 300px; min-height: 65px;` for `size: "normal"`).

---

In addition to that, to support the invisible Turnstile, I think we can add a new option for `size`: `invisible`. The option is just for this library to disable the predetermined height/width, and will not be forwarded to Turnstile.

Thank you!

**Comment by marsidev** [comment]
Hey, thank you for requesting this feature. Has been added in [a9e795e](https://github.com/marsidev/react-turnstile/commit/a9e795ef7aa9e90e665cbb1d14d18b8ecc44a726). This fix the CLS issue.

I would love to add a placeholder to show it while the widget is loading, but I have no found a way to check if the widget is already visible or not.

About the `size: invisible` option, I'm not sure if is viable to add it, because in some cases the widget would need user interaction. Feel free to open another issue or discussion if you want to. Also feel free to contribute 😃

**Comment by chez14** [comment]
Hi @marsidev, thank you so much! To clarify the `size: invisible` part, Cloudflare [mentioned](https://developers.cloudflare.com/turnstile/reference/widget-types/) that there are three types of widgets: managed, non-interactive, and invisible (this were asked upon creation and cannot be changed after that).

Both managed and non-interactive will show a widget and honor the `size`/`data-size` option, but creating an invisible [will not show any widgets at all](https://developers.cloudflare.com/turnstile/reference/widget-types/#invisible) as documented. That's my original concern for the `size: invisible` proposal.

>  because in some cases the widget would need user interaction.

To be honest, I'm still not sure with this part because the doc mentioned that user will not see any widget or indication of browser challenge is in progress. So explicitly for invisible, it will not show any widget, even if it fails. 

I wonder if you mean CF might show something on the page on that section, like [reCaptcha does](https://developers.google.com/recaptcha/docs/versions#recaptcha_v2_invisible_recaptcha_badge), for attribution reasons.

> Also feel free to contribute :smiley:

Ah, then, if this proposal is okay, should I just send you an PR (and reference this issue), or should I create another issue first (then reference the PR to there)?

Thank you!

**Comment by marsidev** [comment]
You are right, only in managed mode there is an user interaction. 

I have no found in the docs a way to choose between modes, maybe is what it's mentioned [here](https://developers.cloudflare.com/turnstile/get-started/migrating-from-recaptcha/).
 
> Turnstile supports:  
• the `render()` call  
• reCAPTCHA v2 invisible mode with the `execute()` call

Yes, open a new issue and submit a PR if you can add it by your own 👍

**Comment by chez14** [comment]
> Yes, open a new issue and submit a PR if you can add it by your own +1

Got it, thank you for the approval, I'll create a new issue and let you know. Thanks!

**Comment by marsidev** [comment]
Thank you!
