### ISSUE TITLE
Putting the widget in a modal?

### ISSUE THREAD

**Issue by NickWoodward** [marsidev/react-turnstile#81]
I'm not entirely sure how to handle this tbh, but I'm looking to render the widget in a modal when it becomes interactive/challenges the user? (So I'm currently using a managed widget that's invisible otherwise).

Your demo [https://codesandbox.io/p/devbox/sweet-dream-s7gcmn?file=%2Fsrc%2Fapp.tsx%3A8%2C20](here), using the ResizeObserver seemed promising, but it's obviously too late by the time it renders.

You also exposed an `onWidgetLoad` callback which sounded good, but you then went on to say that it's only called after `execute()`?

Just wondering if you had any ideas - I'm just fed up of the widget messing with my design/causing CLS and want it out of the way tbh!

Love the package btw, thanks!

**Comment by marsidev** [comment]
To get an invisible widget and make it visible when it becomes interactive, you can use an set the `appearance` to [`interaction-only`](https://developers.cloudflare.com/turnstile/get-started/client-side-rendering/#appearance-modes)

Here is a demo I made: https://codesandbox.io/p/devbox/turnstile-interaction-only-comparison-t6gl2v

**Comment by NickWoodward** [comment]
> To get an invisible widget and make it visible when it becomes interactive, you can use an set the `appearance` to [`interaction-only`](https://developers.cloudflare.com/turnstile/get-started/client-side-rendering/#appearance-modes)
> 
> Here is a demo I made: https://codesandbox.io/p/devbox/turnstile-interaction-only-comparison-t6gl2v

Hi @marsidev, thanks for the reply

I've been doing that but unfortunately the invisible widget has some height, and because it loads in after the rest of my content it causes cls. That's what I was hoping to avoid! :)

**Comment by marsidev** [comment]
I see. I noticed Cloudflare added an extra container to the widget, which for some reason is causing more height than the expected.

Before: `div#cf-turnstile > iframe` 
Now: `div#cf-turnstile > div > iframe`

For now, you can set the second div to `display:flex` to prevent that.

Something like this:

```css
#cf-turnstile div {
  display: flex;
}
```

**Comment by NickWoodward** [comment]
> I see. I noticed Cloudflare added an extra container to the widget, which for some reason is causing more height than the expected.
> 
> Before: `div#cf-turnstile > iframe` Now: `div#cf-turnstile > div > iframe`
> 
> For now, you can set the second div to `display:flex` to prevent that.
> 
> Something like this:
> 
> ```css
> #cf-turnstile div {
>   display: flex;
> }
> ```

Ah, amazing - I thought this behaviour had suddenly started happening XD
Thanks a lot!
