### ISSUE TITLE
🚀 Feature: Allow making the response-field required

### ISSUE THREAD

**Issue by bitofbreeze** [marsidev/react-turnstile#92]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/marsidev/react-turnstile/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

I want to require turnstile to have been completed before clicking submit in a form using the required attribute

**Comment by marsidev** [comment]
Hello, that would be a great adition! 

However, it's not possible to modify the input (or any other element) inside the iframe. Please note `@marsidev/react-turnstile` is an unofficial integration and is not affiliated with Cloudflare.

Alternatively, you can manually check if the widget has been solved. Check [the docs](https://docs.page/marsidev/react-turnstile/get-widget-token) where we mention three ways to obtain the token response.

If you want this feature out of the box, feel free to request it on the [official forum](https://community.cloudflare.com/c/website-application-performance/turnstile/83).
