### ISSUE TITLE
🚀 Feature: React 19 support

### ISSUE THREAD

**Issue by mayocream** [marsidev/react-turnstile#93]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/marsidev/react-turnstile/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Support React 19, as well as Next.js 15 supported it.

**Comment by joepetrillo** [comment]
What issues are you running into?

**Comment by joepetrillo** [comment]
@marsidev Any updates on this? Thanks!
